"""Link to use crypto

Revision ID: 165d1a177ff8
Revises: 0e4c3de4684b
Create Date: 2025-06-17 16:26:40.840710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165d1a177ff8'
down_revision: Union[str, None] = '0e4c3de4684b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('is_virtual', sa.BOOLEAN(), nullable=True))
    conn.execute(sa.text("UPDATE countries SET is_virtual = false WHERE is_virtual IS NULL"))
    op.alter_column('countries', 'is_virtual', nullable=False)
    op.alter_column('countries', 'code_iso',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.add_column('currencies', sa.Column('is_crypto', sa.BOOLEAN(), nullable=True))
    conn.execute(sa.text("UPDATE currencies SET is_crypto = false WHERE is_crypto IS NULL"))
    op.alter_column('currencies', 'is_crypto', nullable=False)

    op.add_column('payment_type', sa.Column('network', sa.VARCHAR(length=20), nullable=True))
    op.add_column('receiving_type', sa.Column('network', sa.VARCHAR(length=20), nullable=True))
    op.add_column('transactions', sa.Column('sender_crypto_address', sa.VARCHAR(length=100), nullable=True))
    op.add_column('transactions', sa.Column('receiver_crypto_address', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'receiver_crypto_address')
    op.drop_column('transactions', 'sender_crypto_address')
    op.drop_column('receiving_type', 'network')
    op.drop_column('payment_type', 'network')
    op.drop_column('currencies', 'is_crypto')
    op.alter_column('countries', 'code_iso',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    op.drop_column('countries', 'is_virtual')
    # ### end Alembic commands ###
