"""change reference

Revision ID: 517ae2888239
Revises: 7ab9ea98fb55
Create Date: 2025-05-15 15:45:53.680908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517ae2888239'
down_revision: Union[str, None] = '7ab9ea98fb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'reference',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.create_index('idx_transaction_reference', 'transactions', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_reference', table_name='transactions')
    op.alter_column('transactions', 'reference',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
