"""add crypto address to payement method

Revision ID: 7930d1a9211c
Revises: 165d1a177ff8
Create Date: 2025-06-20 15:43:04.636241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7930d1a9211c'
down_revision: Union[str, None] = '165d1a177ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_type', sa.Column('crypto_address', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_type', 'crypto_address')
    # ### end Alembic commands ###
