"""xxxx_add_receiver_crypto_field

Revision ID: 884bbb0502f4
Revises: dda3240a4e86
Create Date: 2025-06-22 18:22:54.254493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884bbb0502f4'
down_revision: Union[str, None] = 'dda3240a4e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiving_type', sa.Column('is_crypto_receiver', sa.BOOLEAN(), nullable=False, server_default=sa.text('false')))
    op.alter_column('receiving_type', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.execute("""
           UPDATE receiving_type
           SET is_crypto_receiver = TRUE,
               type = NULL
           WHERE type = 'CRYPTO'
       """)

    op.execute("""
          UPDATE receiving_type
          SET is_crypto_receiver = FALSE
          WHERE is_crypto_receiver IS NULL
      """)

    op.alter_column('receiving_type', 'is_crypto_receiver', server_default=None)

    op.create_unique_constraint('uix_receiving_type_composite', 'receiving_type', ['is_crypto_receiver', 'type', 'network', 'country_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receiving_type', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('receiving_type', 'is_crypto_receiver')
    # ### end Alembic commands ###
