"""xxxx_delete_sender_crypto_field

Revision ID: dda3240a4e86
Revises: f3e5dd3b4cf1
Create Date: 2025-06-22 12:41:02.700924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda3240a4e86'
down_revision: Union[str, None] = 'f3e5dd3b4cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'sender_crypto_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_crypto_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
