"""xxxx_add_is_crypto_field

Revision ID: f3e5dd3b4cf1
Revises: 7930d1a9211c
Create Date: 2025-06-22 10:20:56.737449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e5dd3b4cf1'
down_revision: Union[str, None] = '7930d1a9211c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_type', sa.Column('is_crypto_pay', sa.BOOLEAN(), nullable=False, server_default=sa.text('false')))
    op.alter_column('payment_type', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)


    op.alter_column('payment_type', 'is_crypto_pay', server_default=None)

    op.create_unique_constraint('uix_payment_type_composite', 'payment_type', ['is_crypto_pay', 'type', 'network', 'country_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_payment_type_composite', 'payment_type', type_='unique')
    op.alter_column('payment_type', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('payment_type', 'is_crypto_pay')
    # ### end Alembic commands ###
